version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mlinciko
      POSTGRES_DB: task_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mlinciko
      DB_NAME: task_tracker
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
